/**
 * Agent Worker Logic (Simulated)
 * Extracted from monolith services/agentWorker.js
 */

const agents = {
  documentation: {
    name: 'Documentation Agent',
    process: (input, fileName) => {
      const fnMatches = input.match(/function\s+(\w+)/g) || [];
      return `# Documentation — \`${fileName}\`
## Overview
Module with ${fnMatches.length} functions.
## Functions
${fnMatches.map(f => `- **\`${f}\`** — Implementation detail.`).join('\n')}
*Generated by Kiri Documentation Agent*`;
    }
  },
  code: {
    name: 'Code Agent',
    process: (input, fileName) => {
      return `# Code Generation — \`${fileName}\`
\`\`\`javascript
function helper() {
  console.log("Improved utility function");
}
\`\`\`
*Generated by Kiri Code Agent*`;
    }
  },
  explanation: {
    name: 'Explanation Agent',
    process: (input, fileName) => {
      const lines = input.trim().split('\n');
      return `# Code Explanation — \`${fileName}\`
This file contains ${lines.length} lines. It appears to handle core logic.
*Generated by Kiri Explanation Agent*`;
    }
  },
  search: {
    name: 'Search Agent',
    process: (input, fileName) => {
      return `# Search Results — for "${input.trim().slice(0, 50)}"
1. [MDN Web Docs](https://developer.mozilla.org)
2. [Node.js Docs](https://nodejs.org)
*Generated by Kiri Search Agent*`;
    }
  },
  debug: {
    name: 'Debug Agent',
    process: (input, fileName) => {
      const issues = [];
      if (input.includes('== ')) issues.push('Use strict equality `===` instead of `==`');
      return `# Debug Report — \`${fileName}\`
${issues.length === 0 ? '✅ No issues detected!' : issues.map(i => `- 🔴 ERROR: ${i}`).join('\n')}
*Generated by Kiri Debug Agent*`;
    }
  },
  test: {
    name: 'Test Agent',
    process: (input, fileName) => {
      return `# Test Suite — \`${fileName}\`
\`\`\`javascript
test('module loads', () => { expect(true).toBe(true); });
\`\`\`
*Generated by Kiri Test Agent*`;
    }
  }
};

async function runAgent(agentType, inputData, fileName, onChunk) {
  const agent = agents[agentType];
  if (!agent) throw new Error(`Unknown agent type: ${agentType}`);

  await new Promise(r => setTimeout(r, 800)); // Simulate think time
  const result = agent.process(inputData || '// (empty file)', fileName || 'untitled.js');

  const chunkSize = 80;
  for (let i = 0; i < result.length; i += chunkSize) {
    const chunk = result.slice(i, i + chunkSize);
    if (onChunk) onChunk(chunk);
    await new Promise(r => setTimeout(r, 20)); // Simulate streaming
  }
  return result;
}

module.exports = { runAgent };
