/**
 * Agent Worker Service
 * Simulates intelligent AI agent responses for 6 agent types.
 * In production, this would connect to an LLM API (OpenAI, Gemini, etc.)
 */

const agents = {
  documentation: {
    name: 'Documentation Agent',
    icon: '📝',
    color: '#4fc3f7',
    process: (input, fileName) => {
      const lines = input.trim().split('\n').filter(l => l.trim());
      const fnMatches = input.match(/function\s+(\w+)/g) || [];
      const classMatches = input.match(/class\s+(\w+)/g) || [];

      return `# Documentation — \`${fileName}\`

## Overview
This module contains ${lines.length} lines of code with ${fnMatches.length} function(s) and ${classMatches.length} class(es).

## Functions
${fnMatches.length > 0
  ? fnMatches.map(f => `- **\`${f}\`** — Performs a specific operation as defined in the implementation.`).join('\n')
  : '- No named functions detected'}

## Classes
${classMatches.length > 0
  ? classMatches.map(c => `- **\`${c}\`** — A class that encapsulates related functionality.`).join('\n')
  : '- No classes detected'}

## Usage
\`\`\`javascript
// Import and use this module in your project
const module = require('./${fileName}');
\`\`\`

## Notes
- Ensure all dependencies are installed before running
- Follow the coding standards defined in the project README

*Generated by Kiri Documentation Agent at ${new Date().toISOString()}*`;
    }
  },

  code: {
    name: 'Code Agent',
    icon: '⚡',
    color: '#a5d6a7',
    process: (input, fileName) => {
      const lang = fileName.endsWith('.py') ? 'python' : 'javascript';
      return `# Code Generation — \`${fileName}\`

I've analyzed your code and can suggest the following enhancements:

## Utility Functions

\`\`\`${lang}
${lang === 'javascript' ? `/**
 * Utility: Debounce function to limit rapid calls
 * @param {Function} fn - Function to debounce
 * @param {number} delay - Delay in milliseconds
 */
function debounce(fn, delay) {
  let timer;
  return (...args) => {
    clearTimeout(timer);
    timer = setTimeout(() => fn(...args), delay);
  };
}

/**
 * Utility: Deep clone an object
 * @param {Object} obj - Object to clone
 */
function deepClone(obj) {
  return JSON.parse(JSON.stringify(obj));
}

/**
 * Utility: Async retry with exponential backoff
 * @param {Function} fn - Async function to retry
 * @param {number} retries - Max retry count
 */
async function withRetry(fn, retries = 3) {
  for (let i = 0; i < retries; i++) {
    try { return await fn(); }
    catch (e) { if (i === retries - 1) throw e; await new Promise(r => setTimeout(r, 200 * (i + 1))); }
  }
}

module.exports = { debounce, deepClone, withRetry };` : `def debounce(fn, delay):
    """Debounce a function call by delay seconds."""
    import threading
    timer = None
    def wrapper(*args, **kwargs):
        nonlocal timer
        if timer: timer.cancel()
        timer = threading.Timer(delay, fn, args, kwargs)
        timer.start()
    return wrapper

def deep_clone(obj):
    """Deep clone a dictionary."""
    import copy
    return copy.deepcopy(obj)
`}
\`\`\`

*Generated by Kiri Code Agent at ${new Date().toISOString()}*`;
    }
  },

  explanation: {
    name: 'Explanation Agent',
    icon: '💡',
    color: '#fff176',
    process: (input, fileName) => {
      const lines = input.trim().split('\n');
      const complexity = lines.length < 20 ? 'Low' : lines.length < 100 ? 'Medium' : 'High';
      const hasAsync = /async|await|Promise/.test(input);
      const hasClass = /class\s+\w+/.test(input);
      const hasImport = /require|import/.test(input);

      return `# Code Explanation — \`${fileName}\`

## Summary
This file contains **${lines.length} lines** of code with **${complexity} complexity**.

## Detected Patterns
| Pattern | Detected |
|---------|----------|
| Asynchronous code (async/await) | ${hasAsync ? '✅ Yes' : '❌ No'} |
| Object-Oriented (classes) | ${hasClass ? '✅ Yes' : '❌ No'} |
| Module imports/requires | ${hasImport ? '✅ Yes' : '❌ No'} |

## Line-by-Line Breakdown
${lines.slice(0, 10).map((line, i) => `**Line ${i + 1}:** \`${line.trim() || '(empty)'}\``).join('\n')}
${lines.length > 10 ? `\n... and ${lines.length - 10} more lines` : ''}

## Complexity Analysis
- **Cyclomatic Complexity**: ${complexity}
- **Estimated LOC**: ${lines.filter(l => l.trim() && !l.trim().startsWith('//')).length} (excluding comments)
- **Comment Coverage**: ${Math.round((lines.filter(l => l.trim().startsWith('//')).length / lines.length) * 100)}%

## Recommendations
1. ${complexity === 'High' ? 'Consider breaking this file into smaller modules' : 'Code length is appropriate'}
2. ${hasAsync ? 'Async patterns detected — ensure proper error handling with try/catch' : 'Consider using async patterns for I/O operations'}
3. Add JSDoc comments to public functions for better maintainability

*Generated by Kiri Explanation Agent at ${new Date().toISOString()}*`;
    }
  },

  search: {
    name: 'Search Agent',
    icon: '🔍',
    color: '#ce93d8',
    process: (input, fileName) => {
      const terms = input.trim().split(/\s+/).slice(0, 5);
      return `# Search Results — for "${input.trim().slice(0, 50)}"

## Pattern Matches in \`${fileName}\`
${terms.map((term, i) => `${i + 1}. **\`${term}\`** — Found in code context`).join('\n')}

## Related Documentation
- [MDN Web Docs](https://developer.mozilla.org) — JavaScript reference
- [Node.js Docs](https://nodejs.org/en/docs) — Node.js API documentation
- [npm Registry](https://npmjs.com) — Package registry

## Suggested Resources
| Resource | Description |
|----------|-------------|
| Stack Overflow | Community solutions for common patterns |
| GitHub | Open-source implementations to reference |
| Dev.to | Articles and tutorials |

## Code Snippets (from knowledge base)
\`\`\`javascript
// Common pattern for: ${input.trim().slice(0, 30)}
const result = await Promise.all(
  items.map(item => processItem(item))
);
\`\`\`

*Generated by Kiri Search Agent at ${new Date().toISOString()}*`;
    }
  },

  debug: {
    name: 'Debug Agent',
    icon: '🐛',
    color: '#ef9a9a',
    process: (input, fileName) => {
      const issues = [];
      if (input.includes('var ')) issues.push({ severity: 'warning', line: 'multiple', issue: 'Using `var` instead of `const`/`let`', fix: 'Replace `var` with `const` or `let`' });
      if (input.includes('== ') && !input.includes('=== ')) issues.push({ severity: 'error', line: 'multiple', issue: 'Using loose equality `==` instead of strict `===`', fix: 'Use `===` for strict equality checks' });
      if (!input.includes('try') && (input.includes('await') || input.includes('.then'))) issues.push({ severity: 'warning', line: 'multiple', issue: 'Async operations without try/catch error handling', fix: 'Wrap async calls in try/catch blocks' });
      if (input.includes('console.log')) issues.push({ severity: 'info', line: 'multiple', issue: 'Debug `console.log` statements found', fix: 'Remove console.log before production deployment' });

      const iconMap = { error: '🔴', warning: '🟡', info: '🔵' };

      return `# Debug Report — \`${fileName}\`

## Scan Results
${issues.length === 0
  ? '✅ **No issues detected!** Code looks clean.'
  : `Found **${issues.length} potential issue(s)**:`}

${issues.map((issue, i) => `### ${i + 1}. ${iconMap[issue.severity]} ${issue.severity.toUpperCase()}: ${issue.issue}
- **Location**: ${issue.line}
- **Fix**: ${issue.fix}
`).join('\n')}

## Code Quality Score
\`\`\`
Overall:     ${issues.filter(i => i.severity === 'error').length === 0 ? '████████░░ 80%' : '█████░░░░░ 50%'}
Errors:      ${issues.filter(i => i.severity === 'error').length} found
Warnings:    ${issues.filter(i => i.severity === 'warning').length} found
Info:        ${issues.filter(i => i.severity === 'info').length} found
\`\`\`

## Suggested Fixes
1. Use ESLint for automated code quality checks
2. Enable TypeScript for type safety
3. Add unit tests to catch regressions

*Generated by Kiri Debug Agent at ${new Date().toISOString()}*`;
    }
  },

  test: {
    name: 'Test Agent',
    icon: '🧪',
    color: '#80cbc4',
    process: (input, fileName) => {
      const fnMatches = input.match(/function\s+(\w+)/g) || [];
      const fnNames = fnMatches.map(f => f.replace('function ', ''));

      return `# Test Suite — \`${fileName}\`

## Generated Test Cases

\`\`\`javascript
// Auto-generated tests by Kiri Test Agent
const { describe, test, expect, beforeEach } = require('@jest/globals');

${fnNames.length > 0 ? fnNames.map(fn => `describe('${fn}', () => {
  test('should execute without throwing', () => {
    expect(() => ${fn}()).not.toThrow();
  });

  test('should return expected type', () => {
    const result = ${fn}();
    expect(result).toBeDefined();
  });

  test('should handle edge case: null input', () => {
    expect(() => ${fn}(null)).not.toThrow();
  });
});
`).join('\n') : `describe('${fileName}', () => {
  test('module loads correctly', () => {
    expect(true).toBe(true);
  });

  test('no runtime errors on initialization', () => {
    expect(() => require('./${fileName}')).not.toThrow();
  });
});
`}
\`\`\`

## Test Coverage Plan
| Function | Unit Test | Integration Test | Edge Cases |
|----------|-----------|-----------------|------------|
${fnNames.length > 0
  ? fnNames.map(fn => `| \`${fn}\` | ✅ Generated | 🔲 Pending | ✅ Generated |`).join('\n')
  : '| (no functions) | N/A | N/A | N/A |'}

## Running Tests
\`\`\`bash
npm install --save-dev jest
npx jest ${fileName.replace('.', '.')}.test.js --coverage
\`\`\`

*Generated by Kiri Test Agent at ${new Date().toISOString()}*`;
    }
  }
};

/**
 * Run an agent task asynchronously, emitting progress events via callback
 * @param {string} agentType - Type of agent to run
 * @param {string} inputData - The code/text input
 * @param {string} fileName - The file name for context
 * @param {function} onChunk - Callback called with each text chunk (for streaming)
 * @returns {Promise<string>} - Full result text
 */
async function runAgent(agentType, inputData, fileName, onChunk) {
  const agent = agents[agentType];
  if (!agent) throw new Error(`Unknown agent type: ${agentType}`);

  // Simulate processing delay
  await new Promise(r => setTimeout(r, 800));

  const result = agent.process(inputData || '// (empty file)', fileName || 'untitled.js');

  // Simulate streaming by chunking the result
  const chunkSize = 80;
  for (let i = 0; i < result.length; i += chunkSize) {
    const chunk = result.slice(i, i + chunkSize);
    if (onChunk) onChunk(chunk);
    await new Promise(r => setTimeout(r, 18));
  }

  return result;
}

module.exports = { runAgent, agents };
